//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassengersCounter.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AddressDBEntities : DbContext
    {
        public AddressDBEntities()
            : base("name=AddressDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusStopTable> BusStopTable { get; set; }
        public virtual DbSet<Passenger> Passenger { get; set; }
        public virtual DbSet<Polygon> Polygon { get; set; }
        public virtual DbSet<Shift> Shift { get; set; }
    }
}
