//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassengersCounter.Model
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Passenger
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public string Shift { get; set; }
        public string CoordinatesAddress { get; set; }
        public string busStop { get; set; }
    }
}
