//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassengersCounter.Model
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Polygon
    {
        public int Id { get; set; }
        public string namePolygon { get; set; }
        public string oneCoordinate { get; set; }
        public string twoCoordinate { get; set; }
        public string threeCoordinate { get; set; }
        public string fourCoordinate { get; set; }
    }
}
