//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollector
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hmimesh_Log
    {
        public int ID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int Eventtype { get; set; }
        public int Error_id { get; set; }
        public int Status { get; set; }
        public string Desk_en { get; set; }
        public string Desk_ru { get; set; }
        public int Log_id { get; set; }
    }
}
