//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsedSchalerParserLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Used_schaler
    {
        public int id { get; set; }
        public string PU_id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string UserName { get; set; }
        public Nullable<int> ProdNr { get; set; }
        public string Unknow { get; set; }
        public Nullable<int> TypeFormwork { get; set; }
        public string NameFormwork { get; set; }
    }
}
