//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAllocator
{
    using System;
    using System.Collections.Generic;
    
    public partial class AWM_Rep
    {
        public int ID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Status { get; set; }
        public int Mesh_id { get; set; }
        public string Mesh_name { get; set; }
        public int Rep_id { get; set; }
    }
}
