//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAllocator
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSU_Errors_Log
    {
        public int Error_id { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public int Number { get; set; }
        public int SpsNumber { get; set; }
        public int DischargePos { get; set; }
        public int Recpie { get; set; }
        public int Weighter { get; set; }
        public int Silo { get; set; }
        public int Flag { get; set; }
        public string IntText { get; set; }
        public string Text { get; set; }
        public string LongText { get; set; }
        public Nullable<System.DateTime> Geht { get; set; }
        public Nullable<System.DateTime> Acknowledged { get; set; }
        public Nullable<System.DateTime> DoStart { get; set; }
    }
}
