//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAllocator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leit_Errors
    {
        public int ID { get; set; }
        public System.DateTime StartTime { get; set; }
        public int ErrorNumber { get; set; }
        public string ShortText { get; set; }
        public string LongText { get; set; }
        public int ErrorCode { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int PU_id { get; set; }
    }
}
