//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAllocator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leit_PU
    {
        public int ID { get; set; }
        public int PU_id { get; set; }
        public int StationNumber { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int PalID { get; set; }
        public string CADUniqueId { get; set; }
        public int Timetype { get; set; }
    }
}
