//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAllocator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LOG_ZAVOD_NFEntities : DbContext
    {
        public LOG_ZAVOD_NFEntities()
            : base("name=LOG_ZAVOD_NFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AWM_Dur> AWM_Dur { get; set; }
        public virtual DbSet<AWM_Hmimesh_Log> AWM_Hmimesh_Log { get; set; }
        public virtual DbSet<AWM_Rep> AWM_Rep { get; set; }
        public virtual DbSet<BSU_Errors_Log> BSU_Errors_Log { get; set; }
        public virtual DbSet<BSU_Production> BSU_Production { get; set; }
        public virtual DbSet<Leit_Errors> Leit_Errors { get; set; }
        public virtual DbSet<Leit_PU> Leit_PU { get; set; }
        public virtual DbSet<AWM_HmiCrane_Log> AWM_HmiCrane_Log { get; set; }
    }
}
