//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyCAD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auftrag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auftrag()
        {
            this.Element = new HashSet<Element>();
        }
    
        public string AuftragsNr { get; set; }
        public Nullable<int> Kundennummer { get; set; }
        public string Projektname { get; set; }
        public short Status { get; set; }
        public Nullable<short> AnzElement { get; set; }
        public Nullable<double> Flaechensumme { get; set; }
        public Nullable<short> AnzTransportlose { get; set; }
        public Nullable<System.DateTime> BeginnDatum { get; set; }
        public System.DateTime FertigstellungsDat { get; set; }
        public string Bauvorhaben { get; set; }
        public string Baulos { get; set; }
        public string Bauort { get; set; }
        public string Geschoss { get; set; }
        public string Betreuer { get; set; }
        public string Lieferanschrift { get; set; }
        public string LAStrasse { get; set; }
        public string LA_Ort { get; set; }
        public string LA_PLZ { get; set; }
        public Nullable<short> MusterFlag { get; set; }
        public string InfoText { get; set; }
        public string ProjektInfo2 { get; set; }
        public string ProjektInfo3 { get; set; }
        public Nullable<System.DateTime> Erstellungsdatum { get; set; }
        public string Ersteller { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Element> Element { get; set; }
    }
}
