//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyCAD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CADPalBelegung
    {
        public string AuftragsNr { get; set; }
        public short ElementId { get; set; }
        public short SlabId { get; set; }
        public int FK_PalettenId { get; set; }
        public int ZugriffsId { get; set; }
        public string V_AuftragsNr { get; set; }
        public string V_ZeichnungsNr { get; set; }
        public short V_RevisionsNr { get; set; }
        public short V_SlabId { get; set; }
        public Nullable<double> Belegungsgrad { get; set; }
        public Nullable<double> BetonBindevolumen { get; set; }
        public Nullable<short> BetonBindeguete { get; set; }
        public string domGTTyp { get; set; }
        public string domSteinTyp { get; set; }
        public Nullable<double> SchnittsteinAnt { get; set; }
        public Nullable<short> PalettenProdType { get; set; }
        public Nullable<int> OrdnungsNr { get; set; }
        public Nullable<System.DateTime> Datum1 { get; set; }
        public Nullable<System.DateTime> Datum2 { get; set; }
        public Nullable<int> aenderungsFlag { get; set; }
    }
}
