//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyCAD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Element
    {
        public string AuftragsNr { get; set; }
        public short ElementId { get; set; }
        public string Name { get; set; }
        public string V_AuftragsNr { get; set; }
        public string V_ZeichnungsNr { get; set; }
        public Nullable<short> V_RevisionsNr { get; set; }
        public string ERPSchluessel { get; set; }
        public Nullable<short> VonVorlage { get; set; }
        public Nullable<int> Elementart { get; set; }
        public Nullable<short> Stueckzahl { get; set; }
        public Nullable<short> StueckzahlFertig { get; set; }
        public Nullable<short> Losnummer { get; set; }
        public string LosAuftrag { get; set; }
        public Nullable<short> Lage_im_Los { get; set; }
        public Nullable<short> Montagereihenfolge { get; set; }
        public Nullable<double> Elementgewicht { get; set; }
        public Nullable<double> Elementdicke { get; set; }
        public Nullable<short> ProdHierFertig { get; set; }
        public Nullable<short> Endprodukt_j_n { get; set; }
        public short Status { get; set; }
        public Nullable<double> ZRasterHoehe { get; set; }
        public Nullable<double> Vorsatzdicke_unten { get; set; }
        public Nullable<double> Vorsatzdicke_oben { get; set; }
        public string BMGuete_unten { get; set; }
        public string BMFarbe_unten { get; set; }
        public string BMGuete_oben { get; set; }
        public string BMFarbe_oben { get; set; }
        public Nullable<short> MassivFlag { get; set; }
        public Nullable<double> Fundamentwinkel { get; set; }
        public Nullable<short> Produktionsart { get; set; }
        public Nullable<short> Um_90Grad_dreh { get; set; }
        public Nullable<short> Stapeltype { get; set; }
        public Nullable<double> MaxEBTHoehe { get; set; }
        public Nullable<double> x_min { get; set; }
        public Nullable<double> x_max { get; set; }
        public Nullable<double> y_min { get; set; }
        public Nullable<double> y_max { get; set; }
        public Nullable<double> z_min { get; set; }
        public Nullable<double> z_max { get; set; }
        public string ElmZeichnungsnr { get; set; }
        public Nullable<short> Reklamationswert { get; set; }
        public Nullable<short> DatenStatus { get; set; }
        public Nullable<double> Komplexitaetswert { get; set; }
        public string RevisionsNr { get; set; }
        public string ExterneJobNr { get; set; }
        public string FraechterNr { get; set; }
    
        public virtual Auftrag Auftrag { get; set; }
    }
}
