//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyCAD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Palette
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Palette()
        {
            this.Stationszeiten = new HashSet<Stationszeiten>();
            this.Palettenbelegung = new HashSet<Palettenbelegung>();
        }
    
        public int PalettenID { get; set; }
        public Nullable<int> Palettenart { get; set; }
        public Nullable<int> F_Palettennummer { get; set; }
        public int ProdNr { get; set; }
        public Nullable<int> CADPalId { get; set; }
        public int Produktionsreihenfolge { get; set; }
        public int Auslagerreihenfolge { get; set; }
        public Nullable<short> PalettenProdType { get; set; }
        public Nullable<double> Belegungsgrad { get; set; }
        public Nullable<double> Flaeche { get; set; }
        public Nullable<double> Flaeche_netto { get; set; }
        public Nullable<double> BetonBindevolumen { get; set; }
        public string BetonBindeguete { get; set; }
        public string domGTTyp { get; set; }
        public string MarkupString { get; set; }
        public Nullable<int> SteinAnzahl { get; set; }
        public Nullable<double> SchnittSteinAnt { get; set; }
        public Nullable<short> tkNummer { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<double> belegteBreite { get; set; }
        public Nullable<double> belegteLaenge { get; set; }
        public Nullable<double> belegteDicke { get; set; }
        public Nullable<System.DateTime> Produktionszeit { get; set; }
        public Nullable<int> InfoFlag1 { get; set; }
        public Nullable<short> MusterFlag { get; set; }
        public Nullable<double> aktuelleHoehe { get; set; }
        public Nullable<System.DateTime> geplProdBeginn { get; set; }
        public Nullable<System.DateTime> geplProdEnde { get; set; }
        public Nullable<System.DateTime> simProdBeginn { get; set; }
        public Nullable<System.DateTime> simProdEnde { get; set; }
        public Nullable<System.DateTime> realProdBeginn { get; set; }
        public Nullable<System.DateTime> realProdEnde { get; set; }
        public Nullable<double> geplREFAWert { get; set; }
        public Nullable<int> ExtId { get; set; }
        public Nullable<int> PlannedPalNr { get; set; }
        public double weightEnfAll { get; set; }
        public double weightEnfBrGirders { get; set; }
        public double weightEnfMats { get; set; }
        public double weightEnfRoundsteel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stationszeiten> Stationszeiten { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Palettenbelegung> Palettenbelegung { get; set; }
    }
}
