//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyCAD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Palettenbelegung
    {
        public int PalettenID { get; set; }
        public string FK_AuftragsNr { get; set; }
        public short FK_ElementID { get; set; }
        public short FK_SlabID { get; set; }
        public Nullable<double> NCSortierung { get; set; }
        public Nullable<double> x_Position { get; set; }
        public Nullable<double> y_Position { get; set; }
        public Nullable<double> x_y_Winkel { get; set; }
        public Nullable<double> x_PositionOrig { get; set; }
        public Nullable<double> y_PositionOrig { get; set; }
        public Nullable<double> x_y_WinkelOrig { get; set; }
        public Nullable<short> FK_Losnummer { get; set; }
        public Nullable<short> Passplatte { get; set; }
        public Nullable<short> Schale2ElmId { get; set; }
        public string Schale2AufNr { get; set; }
        public Nullable<int> Schale2PalId { get; set; }
        public Nullable<short> Schale2SlabId { get; set; }
        public Nullable<int> Plazierung { get; set; }
        public string ElmZeichnungsnr { get; set; }
        public bool Defective { get; set; }
    
        public virtual Palette Palette { get; set; }
    }
}
